### ISSUE TITLE
Molt bona idea

### ISSUE THREAD

**Issue by ricardj** [avicarpio/Vacunacio-CatalunyaBOT#1]
Llástima que un cop s'acabi tot ja no serveixi. Ja hagués sigut molt guay que connectant el movil llegis el codi 🙌 

Si hagués sapigut que existía això ho hagues utilitzat segur.

**Comment by avicarpio** [comment]
> Llástima que un cop s'acabi tot ja no serveixi. Ja hagués sigut molt guay que connectant el movil llegis el codi raised_hands
> 
> Si hagués sapigut que existía això ho hagues utilitzat segur.

El següent pas era llegir els sms del mòbil per emplenar-ho automàticament. Però no era tant senzill i no em va motivar lo suficient justament perquè en un parell de mesos serà inútil...

Gràcies pel comentari!!
